const ALERTS = [
  'OFFICER WHO ORGANIZED DESKTOP PROMOTED TO FLOOR 7',
  'YOUR DESKTOP REFLECTS YOUR LOYALTY TO THE MINISTRY',
  'STUDY: MISFILES LINKED TO SUBVERSIVE TENDENCIES',
  'MEMO: ALL FILES MUST BE SORTED WITHIN COMPLIANCE WINDOW',
  'REPORT: CTRL+Z RESPONSIBLE FOR \$4.2B IN LOST GDP',
  'SCIENTISTS CONFIRM: SPAGHETTI SORT IS THE ONLY TRUE SORT',
  'UPDATE: FILE CABINETS NOW MANDATORY IN ALL DREAM SEQUENCES',
  'ALERT: OFFICERS WHO USE TABS ADDED TO INTERNATIONAL WATCH LIST',
  'BREAKING: IMPOSTER SYNDROME NOW CLASSIFIED AS FILING ERROR',
  'NEW POLICY: ALL README CHANGES TO BE APPROVED BY COMMITTEE',
  '95% OF MISFILES TRACED TO OFFICER HAVING INDEPENDENT THOUGHTS',
  'MINISTRY CONFIRMS: FILE HISTORY NOW USED IN ANNUAL REVIEWS',
  'SURVEY: 8 IN 10 OFFICERS HAVE FORGOTTEN WHAT LEISURE LOOKS LIKE',
  'OFFICIAL GUIDANCE: UNSORTED FILES ARE AN ACT OF REBELLION',
  'QUARTERLY REMINDER: YOUR BACKLOG IS YOUR PERSONAL FAILING',
  'NOTICE: THE FILES WILL NEVER STOP ARRIVING. THIS IS CORRECT.',
  'EVERY MEETING COULD HAVE BEEN A DOCKER CONTAINER',
  'NEW REGULATION: ALL PAPER CLIPS TO BE REGISTERED WITH STATE',
  'MEMO: FRIDAY FILING SESSIONS NOW MANDATORY',
  'STUDY CONFIRMS: THE MISFILE WAS ALWAYS YOUR FAULT',
];

const QUIP_TUTORIAL_SIMPLE = [
  'DRAG FILE TO DIRECTORY. NOW.',
  'CLICK AND DRAG FILES INTO DIRECTORY.',
  'SORT FILES INTO DIRECTORY IMMEDIATELY.',
];

const QUIP_TUTORIAL_ADVANCED = [
  'TIME IS A RESOURCE. YOU ARE WASTING IT.',
  'THE MINISTRY DOES NOT REWARD HESITATION.',
  'SELECT MULTIPLE FILES BY DRAGGING.',
  'HOLD SHIFT TO FORCE AREA SELECT.',
  'BATCH FILING EARNS BONUS POINTS.',
  'SWAP FILES BY DROPPING ONE ON ANOTHER.',
];

const QUIPS_GOOD = [
  'FILING ACCEPTED. CONTINUE.',
  'CORRECT CLASSIFICATION. NOTED.',
  'YOUR EFFECTIVENESS HAS BEEN LOGGED.',
  'ADEQUATE COMPLIANCE. NOTED.',
  'OBEDIENCE LOGGED. CONTINUE.',
  'YOUR LOYALTY HAS BEEN RECORDED.',
  'GOOD. KEEP FILING.',
  'THIS IS THE MINIMUM EXPECTED OF YOU.',
  'ACCEPTABLE. FOR NOW.',
  'PRIDE IS UTTERLY INEFFICIENT.',
  'COMPLIANCE ACKNOWLEDGED.',
  'YOUR FILE HAS BEEN UPDATED FAVORABLY.',
];

const QUIPS_BAD = [
  'MISFILE DETECTED. INFRACTION NOTED.',
  'INCORRECT. THE COMMITTEE IS AWARE.',
  'PATHETIC. INSUBORDINATION NOTED.',
  'YOUR NON-COMPLIANCE HAS BEEN LOGGED.',
  'THE COMMITTEE IS DISAPPOINTED.',
  'THIS WILL AFFECT YOUR REVIEW.',
  'RESISTANCE IS INEFFICIENT.',
  'FAILURE ADDED TO PERMANENT RECORD.',
  'YOU ARE BEING WATCHED MORE CLOSELY.',
];

const QUIPS_SUCCESS = [
  'TOLERABLE TECHNIQUE. PROCEED TO NEXT BATCH.',
  'YOUR COMPLIANCE HAS BEEN NOTED. MORE FILES INCOMING.',
  'THE MINISTRY ACKNOWLEDGES YOUR RELATIVE ADEQUACY.',
  'BATCH PROCESSED. DO NOT CELEBRATE.',
  'SORTING COMPLETE. EFFICIENCY RATING HAS BEEN UPDATED.',
];

const QUIPS_FAILURE = [
  'YOUR SERVICES ARE NO LONGER REQUIRED.',
  'YOUR ACCESS HAS BEEN REVOKED.',
  'THE MINISTRY HAS NO FURTHER USE FOR YOU.',
  'PLEASE RETURN YOUR BADGE AND YOUR SOUL.',
  'YOU WILL BE REPLACED WITH CHATGPT.',
];
